# Generated by Django 2.1.7 on 2019-03-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('ph_number', models.CharField(default='', error_messages={'code': 123}, max_length=11, unique=True, verbose_name='电话号码')),
                ('nick_name', models.CharField(default='', max_length=12, unique=True, verbose_name='昵称')),
                ('image', models.ImageField(default='image/default.jpg', upload_to='image/%Y/%M', verbose_name='头像')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
