# Generated by Django 2.1.7 on 2019-04-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='back_user',
            name='phnumber',
            field=models.CharField(default='', max_length=11, unique=True),
        ),
        migrations.AddField(
            model_name='back_user',
            name='truename',
            field=models.CharField(default='', max_length=40),
        ),
    ]
