# Generated by Django 2.1.7 on 2019-04-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='back_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=15)),
                ('password', models.CharField(default='', max_length=15)),
            ],
            options={
                'verbose_name': '管理人员',
                'verbose_name_plural': '管理人员',
            },
        ),
    ]
