# Generated by Django 2.1.7 on 2019-04-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190418_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='back_user',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, default='2019-04-01'),
            preserve_default=False,
        ),
    ]
