# Generated by Django 2.1.7 on 2019-04-27 10:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190418_1220'),
    ]

    operations = [


    ]
