# Generated by Django 2.1.7 on 2019-04-27 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190427_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('num', models.IntegerField()),
            ],
            options={
                'verbose_name': '活跃人数',
                'verbose_name_plural': '活跃人数',
            },
        ),

    ]
