# Generated by Django 2.1.7 on 2019-04-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190406_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_very',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('very_code', models.CharField(max_length=10, verbose_name='验证码')),
                ('op_type', models.IntegerField(verbose_name='操作类型')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
    ]
