# Generated by Django 2.1.7 on 2019-04-07 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('三分', models.FloatField()),
                ('助攻', models.FloatField()),
                ('命中率', models.FloatField()),
                ('场次', models.FloatField()),
                ('失误', models.FloatField()),
                ('得分', models.FloatField()),
                ('投篮', models.FloatField()),
                ('抢断', models.FloatField()),
                ('时间', models.FloatField()),
                ('犯规', models.FloatField()),
                ('盖帽', models.FloatField()),
                ('篮板', models.FloatField()),
                ('罚球', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('头像', models.ImageField(upload_to='')),
                ('中文名', models.CharField(max_length=30)),
                ('位置', models.CharField(max_length=20)),
                ('体重', models.CharField(max_length=30)),
                ('合同', models.CharField(max_length=200)),
                ('国际', models.CharField(max_length=50)),
                ('学校', models.CharField(max_length=100)),
                ('序号', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('本赛季薪金', models.CharField(max_length=20)),
                ('球队', models.CharField(max_length=20)),
                ('生日', models.CharField(max_length=20)),
                ('英文名', models.CharField(max_length=20)),
                ('身高', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('序号', models.IntegerField(primary_key=True, serialize=False)),
                ('排名', models.IntegerField()),
                ('数值', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('球队名', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('主教练', models.CharField(max_length=20)),
                ('介绍', models.CharField(default='', max_length=300)),
                ('队标', models.ImageField(upload_to='')),
                ('进入NBA', models.CharField(max_length=20)),
                ('场均助攻', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='助攻信息', to='persons.Record')),
                ('场均失分', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='失分信息', to='persons.Record')),
                ('场均失误', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='失误信息', to='persons.Record')),
                ('场均得分', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='得分信息', to='persons.Record')),
                ('场均篮板', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='篮板信息', to='persons.Record')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='球队名',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Team', verbose_name='所属球队'),
        ),
        migrations.AddField(
            model_name='career',
            name='序号',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Player'),
        ),
    ]
