# Generated by Django 2.1.7 on 2019-04-04 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('ppg', models.FloatField()),
                ('rpg', models.FloatField()),
                ('apg', models.FloatField()),
                ('mpg', models.FloatField()),
                ('topg', models.FloatField()),
                ('spg', models.FloatField()),
                ('bpg', models.FloatField()),
                ('tpp', models.FloatField()),
                ('ftp', models.FloatField()),
                ('fgp', models.FloatField()),
                ('steals', models.IntegerField()),
                ('turnovers', models.IntegerField()),
                ('offReb', models.IntegerField()),
                ('defReb', models.IntegerField()),
                ('totReb', models.IntegerField()),
                ('fgm', models.IntegerField()),
                ('fga', models.IntegerField()),
                ('ftm', models.IntegerField()),
                ('fta', models.IntegerField()),
                ('pFouls', models.IntegerField()),
                ('points', models.IntegerField()),
                ('gamesPlayed', models.IntegerField()),
                ('gamesStarted', models.IntegerField()),
                ('plusMinus', models.IntegerField()),
                ('mins', models.IntegerField()),
            ],
            options={
                'verbose_name': '职业生涯',
                'verbose_name_plural': '职业生涯',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('personId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('collegeName', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('dateOfBirthUTC', models.DateField(auto_now_add=True)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('heightFeet', models.FloatField()),
                ('heightInches', models.FloatField()),
                ('heightMeters', models.FloatField()),
                ('nbaDebutYear', models.DateField(auto_now_add=True)),
                ('temporaryDisplayName', models.CharField(max_length=50)),
                ('weightKilograms', models.FloatField()),
                ('weightPounds', models.FloatField(verbose_name='')),
                ('playerLogo', models.ImageField(upload_to='media/player/image', verbose_name='球员头像')),
            ],
            options={
                'verbose_name': '球员',
                'verbose_name_plural': '球员',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('teamname', models.CharField(max_length=50, verbose_name='队伍名')),
                ('teamLogo', models.ImageField(upload_to='media/team/image', verbose_name='队伍图标')),
            ],
            options={
                'verbose_name': '球队',
                'verbose_name_plural': '球队',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='teamId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Team', verbose_name='所属球队'),
        ),
        migrations.AddField(
            model_name='career',
            name='personId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Player', verbose_name='所属球员'),
        ),
    ]
