# Generated by Django 2.1.7 on 2019-04-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='teamname',
        ),
        migrations.AddField(
            model_name='team',
            name='primaryColor',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='secondaryColor',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='ttsName',
            field=models.CharField(default='', max_length=50, verbose_name='队伍名'),
        ),
        migrations.AlterField(
            model_name='player',
            name='playerLogo',
            field=models.ImageField(null=True, upload_to='media/player', verbose_name='球员头像'),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamId',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='队伍编号'),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamLogo',
            field=models.ImageField(upload_to='media/team', verbose_name='队伍图标'),
        ),
    ]
