# Generated by Django 2.1.7 on 2019-04-11 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='国际',
            new_name='国籍',
        ),
        migrations.AddField(
            model_name='career',
            name='类型',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='选秀',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='球队中文名',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='career',
            name='三分',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='career',
            name='助攻',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='career',
            name='命中率',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='career',
            name='场次',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='career',
            name='失误',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='career',
            name='序号',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='persons.Player'),
        ),
        migrations.AlterField(
            model_name='career',
            name='得分',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='career',
            name='投篮',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='career',
            name='抢断',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='career',
            name='时间',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='career',
            name='犯规',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='career',
            name='盖帽',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='career',
            name='篮板',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='career',
            name='罚球',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='球队名',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='persons.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='英文名',
            field=models.CharField(max_length=50),
        ),
    ]
