# Generated by Django 2.1.7 on 2019-04-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20190416_1123'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='match_teamsummary',
        #     name='home_away',
        #     field=models.IntegerField(default=0),
        #     preserve_default=False,
        # ),
    ]
