# Generated by Django 2.1.7 on 2019-04-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20190411_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='球队中文名',
        ),
    ]
