# Generated by Django 2.1.7 on 2019-04-19 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20190419_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('赛季球队', models.CharField(max_length=50)),
                ('主队', models.CharField(max_length=50)),
                ('客队', models.CharField(max_length=20)),
                ('主队比分', models.CharField(max_length=10)),
                ('客队比分', models.CharField(max_length=10)),
                ('结果', models.CharField(max_length=10)),
                ('日期', models.CharField(max_length=20)),
                ('北京时间', models.CharField(max_length=20)),
                ('类型', models.CharField(max_length=10)),
                ('比赛id',
                 models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='persons.Match')),
            ],
        ),
    ]
