# Generated by Django 2.1.7 on 2019-04-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20190412_2147'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='match',
        #     name='主场总分',
        # ),
        # migrations.RemoveField(
        #     model_name='match',
        #     name='主场第一节',
        # ),
        # migrations.RemoveField(
        #     model_name='match',
        #     name='主场第三节',
        # ),
        # migrations.RemoveField(
        #     model_name='match',
        #     name='主场第二节',
        # ),
        # migrations.RemoveField(
        #     model_name='match',
        #     name='主场第四节',
        # ),
        # migrations.RemoveField(
        #     model_name='match',
        #     name='客场总分',
        # ),
        # migrations.RemoveField(
        #     model_name='match',
        #     name='客场第一节',
        # ),
        # migrations.RemoveField(
        #     model_name='match',
        #     name='客场第三节',
        # ),
        # migrations.RemoveField(
        #     model_name='match',
        #     name='客场第二节',
        # ),
        # migrations.RemoveField(
        #     model_name='match',
        #     name='客场第四节',
        # ),
    ]
