# Generated by Django 2.1.7 on 2019-04-20 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20190419_1758'),
    ]

    operations = [

    ]
