# Generated by Django 2.1.7 on 2019-04-20 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_auto_20190420_1743'),
    ]

    operations = [

        migrations.AddField(
            model_name='schedule',
            name='英文名',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),

    ]
