# Generated by Django 2.1.7 on 2019-04-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_team_球队中文名'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='球队中文名',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
