# Generated by Django 2.1.7 on 2019-05-05 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_auto_20190420_1752'),
    ]

    operations = [

        migrations.AddField(
            model_name='match',
            name='时间',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='状态',
            field=models.IntegerField(default=1),
        ),

    ]
