# Generated by Django 2.1.7 on 2019-04-16 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_remove_match_teamsummary_home_away'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match_teamsummary',
            name='home_away',
        ),
    ]
