# Generated by Django 2.1.7 on 2019-04-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_team_球队中文名'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='team',
        #     name='球队中文名',
        # ),
    ]
