# Generated by Django 2.1.7 on 2019-04-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_auto_20190405_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='assists',
            field=models.IntegerField(default=0, verbose_name='助攻数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='blocks',
            field=models.IntegerField(default=0, verbose_name='盖帽数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='teamId',
            field=models.CharField(default='', max_length=12, verbose_name='球队编号'),
            preserve_default=False,
        ),
    ]
