# Generated by Django 2.1.7 on 2019-04-11 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_team_球队中文名'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('球员名', models.CharField(max_length=30)),
                ('位置', models.CharField(max_length=10)),
                ('时间', models.CharField(max_length=10)),
                ('投篮', models.CharField(max_length=10)),
                ('三分', models.CharField(max_length=10)),
                ('罚球', models.CharField(max_length=10)),
                ('前场', models.CharField(max_length=10)),
                ('后场', models.CharField(max_length=10)),
                ('篮板', models.CharField(max_length=10)),
                ('助攻', models.CharField(max_length=10)),
                ('犯规', models.CharField(max_length=10)),
                ('抢断', models.CharField(max_length=10)),
                ('失误', models.CharField(max_length=10)),
                ('封盖', models.CharField(max_length=10)),
                ('得分', models.CharField(max_length=10)),
                ('正负', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='命中率',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='命中率信息', to='persons.MatchPlayer'),
        ),
        migrations.AddField(
            model_name='match',
            name='统计',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='统计信息', to='persons.MatchPlayer'),
        ),
    ]
