# Generated by Django 2.1.7 on 2019-04-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_auto_20190410_0113'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='career',
        #     name='序号',
        # ),
    ]
