# Generated by Django 2.1.7 on 2019-05-07 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_auto_20190507_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('管理员', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('球队名', models.CharField(max_length=40)),
                ('球员名', models.CharField(max_length=40)),
                ('位置', models.CharField(max_length=10)),
                ('得分', models.CharField(max_length=10)),
                ('篮板', models.CharField(max_length=10)),
                ('三分', models.CharField(max_length=10)),
                ('罚球', models.CharField(max_length=10)),
                ('抢断', models.CharField(max_length=10)),
                ('助攻', models.CharField(max_length=10)),
                ('失误', models.CharField(max_length=10)),
                ('号码', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MyGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('名称', models.CharField(max_length=40)),
                ('简介', models.CharField(max_length=300)),
                ('时间', models.CharField(max_length=40)),
                ('创建时间', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('创建者', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='MyMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('日期', models.CharField(max_length=20)),
                ('时间', models.CharField(max_length=20)),
                ('地点', models.CharField(max_length=40)),
                ('主场', models.CharField(max_length=40)),
                ('客场', models.CharField(max_length=40)),
                ('主场第一节', models.CharField(default='0', max_length=10)),
                ('主场第二节', models.CharField(default='0', max_length=10)),
                ('主场第三节', models.CharField(default='0', max_length=10)),
                ('主场第四节', models.CharField(default='0', max_length=10)),
                ('主场加时1', models.CharField(default='0', max_length=10)),
                ('主场加时2', models.CharField(default='0', max_length=10)),
                ('主场加时3', models.CharField(default='0', max_length=10)),
                ('主场加时4', models.CharField(default='0', max_length=10)),
                ('客场第一节', models.CharField(default='0', max_length=10)),
                ('客场第二节', models.CharField(default='0', max_length=10)),
                ('客场第三节', models.CharField(default='0', max_length=10)),
                ('客场第四节', models.CharField(default='0', max_length=10)),
                ('客场加时1', models.CharField(default='0', max_length=10)),
                ('客场加时2', models.CharField(default='0', max_length=10)),
                ('客场加时3', models.CharField(default='0', max_length=10)),
                ('客场加时4', models.CharField(default='0', max_length=10)),
                ('主场总分', models.CharField(default='0', max_length=10)),
                ('客场总分', models.CharField(default='0', max_length=10)),
                ('加时场数', models.IntegerField(default=0)),
                ('赛程', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymatch.MyGame')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('用户', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='关注者', to='user.User')),
                ('赛程', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymatch.MyGame')),
            ],
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='比赛',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymatch.MyMatch'),
        ),
        migrations.AddField(
            model_name='gamemanager',
            name='赛程',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymatch.MyGame'),
        ),
    ]
